export default {
  INCREMENT: "INCREMENT",
  INCREMENT_LINK: "INCREMENT_LINK",
  INCREMENT_NOTE: "INCREMENT_NOTE",
  INCREMENT_BLOG: "INCREMENT_BLOG",
  TOGGLE_BLOG: "TOGGLE_BLOG",
  TOGGLE_NOTE: "TOGGLE_NOTE",
  TOGGLE_LINK: "TOGGLE_LINK",
}
